[versions]
accompanist = "0.34.0"
android-gradlePlugin = "8.5.0"
androidx-activity = "1.9.0"
androidx-appCompat = "1.7.0"
androidx-compose-bom = "2024.05.00"
androidx-lifecycle = "2.7.0"
androidx-navigation = "2.7.7"
androidx-savedstate = "1.2.1"
androidx-core = "1.13.1"
androidx-window = "1.3.0"
coil = "2.6.0"
compileSdk = "34"
datastore = "1.1.1"
dependencyGuard = "0.5.0"
dokka = "1.9.20"
junit = "4.13.2"
kotlin = "2.0.0"
kotlinx-coroutines = "1.8.1"
kotlinx-collections-immutable = "0.3.7"
kotlinx-serialization-json = "1.6.3"
ksp = "2.0.0-1.0.21"
ktlint = "1.2.1"
lint = "31.5.0"
minCompileSdk = "24"
paparazzi = "1.3.4"
showkase = "1.0.3"
slackLint = "1.3.1"
spotless = "6.25.0"
targetSdk = "34"
testParameterInjector = "1.16"

[libraries]

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-testharness = { module = "com.google.accompanist:accompanist-testharness", version.ref = "accompanist" }

airbnb-showkase = { module = "com.airbnb.android:showkase", version.ref = "showkase" }
airbnb-showkase-processor = { module = "com.airbnb.android:showkase-processor", version.ref = "showkase" }

androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
# https://androidx.tech/artifacts/appcompat/appcompat-resources/
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }
androidx-appCompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx-appCompat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class"}
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
# https://developer.android.com/reference/kotlin/androidx/compose/ui/text/googlefonts/package-summary
androidx-compose-ui-text = { module = "androidx.compose.ui:ui-text-google-fonts" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-testManifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-savedstate = { module = "androidx.savedstate:savedstate-ktx", version.ref = "androidx-savedstate" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }
# https://mvnrepository.com/artifact/androidx.test.ext/truth
androidx-test-runner = { module = "androidx.test:runner", version = "1.5.2" }
androidx-test-truth = { module = "androidx.test.ext:truth", version = "1.5.0" }
# https://coil-kt.github.io/coil/
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# https://developer.android.com/topic/libraries/architecture/datastore
androidx-datastore = { module = "androidx.datastore:datastore" , version.ref = "datastore" }

# Docs: https://developer.android.com/studio/write/java8-support#library-desugaring
# Changelog: https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md
desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.4" }

dokka-android-documentation-plugin = { module = "org.jetbrains.dokka:android-documentation-plugin", version.ref = "dokka" }
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }

gradlePlugins-android = { module = "com.android.tools.build:gradle", version.ref = "android-gradlePlugin" }
gradlePlugins-compose = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
gradlePlugins-dependencyGuard = { module = "com.dropbox.dependency-guard:com.dropbox.dependency-guard.gradle.plugin", version.ref = "dependencyGuard" }
gradlePlugins-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradlePlugins-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugins-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
gradlePlugins-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

junit = { module = "junit:junit", version.ref = "junit" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

ktlint-bom = { module = "com.pinterest.ktlint:ktlint-bom", version.ref = "ktlint" }

lint = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }

# https://github.com/robolectric/robolectric
robolectric = { module = "org.robolectric:robolectric", version = "4.12.2" }

slack-lint-compose = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "slackLint" }

# https://github.com/google/TestParameterInjector
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "testParameterInjector" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradlePlugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-gradlePlugin" }
android-lint = { id = "com.android.lint", version.ref = "android-gradlePlugin" }
android-test = { id = "com.android.test", version.ref = "android-gradlePlugin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
