name: 'ğŸ‘· Build â†’ ğŸ§‘â€ğŸ”¬ Test â†’ ğŸ•µï¸ Lint'

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6 # v1.0.5

  build_test_lint:
    needs: validation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'ğŸ‘· Build'
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
        with:
          arguments: assembleRelease
      - name: 'ğŸ§‘â€ğŸ”¬ Test'
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
        with:
          arguments: testReleaseUnitTest
      - name: 'ğŸ•µï¸ Lint'
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
        with:
          arguments: lintRelease
