name: 'ğŸ‘· Build â†’ ğŸ§‘â€ğŸ”¬ Test â†’ ğŸ•µï¸ Lint'

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: ./.github/actions/setup-gradle-properties
      - uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6 # v1.0.5
      - uses: actionsdesk/lfs-warning@e5f9a4c21f4bee104db7c0f23954dde59e5df909 # v3.2
      - uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
        with:
          arguments: dependencyGuard --quiet

  build-test-lint:
    needs: validation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 'ğŸ˜ Setup Gradle'
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3

      - name: 'ğŸ‘· Build'
        id: build
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
        with:
          arguments: assembleRelease
      - name: 'ğŸ“¦ Archive AARs'
        uses: actions/upload-artifact@v3
        with:
          name: aar
          path: '**/build/outputs/aar'
      - name: 'ğŸ“¢ Diffuse report'
        if: ${{ always() && steps.build.outcome == 'success' }}
        uses: ./.github/actions/diffuse-aar
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}

      - name: 'ğŸ§‘â€ğŸ”¬ Test'
        id: test
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
        with:
          arguments: testReleaseUnitTest
      - name: 'ğŸ“¦ Archive JUnit reports'
        if: ${{ always() && contains(fromJSON('["success", "failure"]'), steps.test.outcome) }}
        uses: ./.github/actions/archive-junit-reports
        with:
          html: '**/build/reports/tests/testReleaseUnitTest'
          xml: '**/build/test-results/testReleaseUnitTest/**.xml'

      - name: 'ğŸ•µï¸ Lint'
        id: lint
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
        with:
          arguments: lintRelease
      - name: 'ğŸ“¦ Archive Lint reports'
        uses: ./.github/actions/archive-lint-reports
        with:
          analysis: '/'
          html: '**/build/reports/lint-results-*.html'
          sarif: '**/build/reports/lint-results-*.sarif'
          xml: '**/build/reports/lint-results-*.xml'
